# Generated by Django 6.0.7 on 2026-07-21 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('module', models.CharField(choices=[('clients', 'Clientes'), ('processes', 'Processos'), ('calendar', 'Calendário'), ('documents', 'Documentos'), ('users', 'Usuários'), ('others', 'Outros')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('in_analysis', 'Em Análise'), ('waiting_user', 'Esperando Usuário'), ('resolved', 'Resolvido'), ('closed', 'Fechado')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
